repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    # -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: debug-statements
    -   id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.14.0
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black==23.3.0
